kafka:
  bootstrap_servers: "localhost:9092"
  services:
    auth-service:
      name: "auth"
      url: "localhost:5005"
      topic: "auth-service-topic"
      role: "publisher"
    user-service:
      name: "user"
      url: "localhost:5001"
      topic: "user-service-topic"
      role: "subscriber"
      subscribes_to:
        - "auth-service-topic"
