kafka:
  bootstrap_servers: "localhost:9092"
  services:
    auth-service:
      topic: "auth-service-topic"
      role: "publisher"   # This service publishes messages
    user-service:
      topic: "user-service-topic"
      role: "subscriber"  # This service subscribes to the auth-service-topic
      subscribes_to:
        - "auth-service-topic"
    product-service:
      topic: "product-service-topic"
      role: "both"        # Both publishes and subscribes as needed